// <auto-generated />
namespace Timesheet.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<Db.TimesheetDbContext>)>]
type TimesheetDbContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "5.0.7")
            |> ignore

        modelBuilder.Entity("Db+Channel", (fun b ->

            b.Property<string>("Id")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Json")
                .HasColumnType("TEXT") |> ignore
            b.Property<DateTimeOffset>("LastDownload")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Name")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("TeamName")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Channels") |> ignore

        )) |> ignore

        modelBuilder.Entity("Db+ChannelMessage", (fun b ->

            b.Property<string>("ChannelId")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Id")
                .HasColumnType("TEXT") |> ignore
            b.Property<DateTimeOffset>("Created")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Json")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("ChannelId", "Id") |> ignore

            b.ToTable("ChannelMessages") |> ignore

        )) |> ignore

        modelBuilder.Entity("Db+Chat", (fun b ->

            b.Property<string>("Id")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Json")
                .HasColumnType("TEXT") |> ignore
            b.Property<DateTimeOffset>("LastDownload")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Name")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("Chats") |> ignore

        )) |> ignore

        modelBuilder.Entity("Db+ChatMessage", (fun b ->

            b.Property<string>("ChatId")
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Id")
                .HasColumnType("TEXT") |> ignore
            b.Property<DateTimeOffset>("Created")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Json")
                .HasColumnType("TEXT") |> ignore

            b.HasKey("ChatId", "Id") |> ignore

            b.ToTable("ChatMessages") |> ignore

        )) |> ignore

        modelBuilder.Entity("Db+ChannelMessage", (fun b ->
            b.HasOne("Db+Channel",null)
                .WithMany("Messages")
                .HasForeignKey("ChannelId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

        modelBuilder.Entity("Db+ChatMessage", (fun b ->
            b.HasOne("Db+Chat",null)
                .WithMany("Messages")
                .HasForeignKey("ChatId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired() |> ignore
        )) |> ignore

